package exception_handling;

public class Nested_try_catch {

	public static void main(String[] args) {
				                           
		try
		{
			try
			{
				
			}
			catch(Exception e)
			{
				
			}
		}
		catch(Exception e)
		{
			
		}
		//this is called as nested try catch

	}

}
